worker_processes auto;

events {
    worker_connections 460;
}

http {
    upstream frauddetection {
        server api01:8080;
        server api02:8080;
    }
    server {
        listen 9999;

        location / {
            proxy_pass http://frauddetection;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}